import { isNil, isObject } from '../utils/is.js';
import { assignOwnKey } from '../internal/path.js';

/**
 * Creates an object with the same keys as object and values generated by
 * running each own enumerable string keyed property of object through
 * iteratee. The iteratee is invoked with three arguments:
 * (value, key, object).
 *
 * @param object - The object to iterate over
 * @param iteratee - The function invoked per iteration
 * @returns The new mapped object
 *
 * @example
 * ```ts
 * const users = {
 *   'fred':    { 'user': 'fred',    'age': 40 },
 *   'pebbles': { 'user': 'pebbles', 'age': 1 }
 * };
 *
 * mapValues(users, function(o) { return o.age; });
 * // => { 'fred': 40, 'pebbles': 1 } (iteration order is not guaranteed)
 *
 * // The `_.property` iteratee shorthand.
 * mapValues(users, 'age');
 * // => { 'fred': 40, 'pebbles': 1 } (iteration order is not guaranteed)
 * ```
 */
export function mapValues<T extends object, R>(
  object: T,
  iteratee: ((value: any, key: string, object: T) => R) | string
): Record<string, R> {
  if (!isObject(object)) {
    return {} as Record<string, R>;
  }

  // Convert iteratee to a function if it's a string
  let iterateeFn: (value: any, key: string, object: T) => R;

  if (typeof iteratee === 'string') {
    const key = iteratee;
    iterateeFn = (value: any) => (isNil(value) ? (undefined as any) : (value[key] as R));
  } else {
    iterateeFn = iteratee;
  }

  const result: Record<string, R> = {};

  for (const key in object) {
    if (Object.prototype.hasOwnProperty.call(object, key)) {
      assignOwnKey(result, key, iterateeFn((object as any)[key], key, object));
    }
  }

  return result;
}

/**
 * Creates an object with the same values as object and keys generated
 * by running each own enumerable string keyed property of object through
 * iteratee. The iteratee is invoked with three arguments:
 * (value, key, object).
 *
 * @param object - The object to iterate over
 * @param iteratee - The function invoked per iteration
 * @returns The new mapped object
 *
 * @example
 * ```ts
 * mapKeys({ 'a': 1, 'b': 2 }, function(value, key) {
 *   return key + value;
 * });
 * // => { 'a1': 1, 'b2': 2 }
 * ```
 */
export function mapKeys<T extends object>(
  object: T,
  iteratee: (value: any, key: string, object: T) => string
): Record<string, any> {
  if (!isObject(object)) {
    return {} as Record<string, any>;
  }

  const result: Record<string, any> = {};

  for (const key in object) {
    if (Object.prototype.hasOwnProperty.call(object, key)) {
      const value = (object as any)[key];
      const newKey = iteratee(value, key, object);
      assignOwnKey(result, newKey, value);
    }
  }

  return result;
}
